.TH LV2CONFIG 1 "March 20, 2011"
.SH NAME
\fBlv2config\fP \- build an LV2 #include directory tree
.SH SYNOPSIS
.B lv2config
.br
.B lv2config
.RI INCLUDE_DIR
.br
.B lv2config
.RI INCLUDE_DIR
.RI BUNDLES_DIR
.SH DESCRIPTION
.B lv2config
is a utility to build an LV2 #include directory tree for a set of LV2
extensions (and the "core" specification), which must be run after
installing extensions to allow compiling code that uses those extensions.
This allows code to use a universal #include style based directly on
the URI of the extension.
.PP
For example, the
.IR #include
statement for the LV2 core specification which has URI
.I http://lv2plug.in/ns/ext/lv2core
is:
.PP
.RS 5
\fB#include "lv2/lv2plug.in/ns/ext/lv2core/lv2.h"\fR
.RE
.PP
(lv2.h is simply a file that resides in the lv2core bundle, there may be
several such files).
.PP
.B lv2config
can be used to build an include directory tree for all installed LV2
extensions, or used to build a local include directory tree for projects
that wish to include extensions in their source trees rather than use
the system installed versions.
.PP
.B lv2config
must be run after an extension is installed to enable compiling against
that extension. Its name is deliberately analogous to \fBldconfig\fP
since the concept is similar: to use an installed extension/library,
you must first run \fBlv2config/ldconfig\fP.
.PP
.SH OPTIONS
When running without options, lv2config builds the default system
LV2 include directories.
.PP
If only INCLUDE_DIR is set, it builds an LV2 include directory tree
at INCLUDE_DIR for all extensions found in $LV2_PATH.
.PP
When both INCLUDE_DIR and BUNDLES_DIR parameters are set, it builds
an LV2 include directory tree at INCLUDE_DIR for all extensions found
in bundles under BUNDLES_DIR.
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
show usage and exit
.SH ENVIRONMENT
All directories in LV2_PATH are searched if BUNDLES_DIR is unspecified.
.PP
DESTDIR is prepended to both INCLUDE_DIR and BUNDLES_DIR to facilitate
packaging.
.SH AUTHOR
lv2config was written by David Robillard <d@drobilla.net>.
.PP
This manual page was written by Jaromír Mikeš <mira.mikes@seznam.cz>,
Alessio Treglia <alessio@debian.org>, and David Robillard <d@drobilla.net>.
