#!/usr/bin/env python
import os

from waflib.extras import autowaf as autowaf
import waflib.Logs as Logs

import literasc

def confgure(conf):
    pass

def bld_book_src(task):
    filenames = []
    for i in task.inputs:
        filenames += [i.abspath()]

    literasc.gen(open(task.outputs[0].abspath(), 'w'), filenames)

    
def build(bld):
    files = [bld.path.find_node('README.txt')]
    for i in bld.path.ant_glob('*', src=False, dir=True):
        for j in bld.path.ant_glob('%s/*.*' % i):
            name = j.abspath()
            if (name.endswith('.c') or
                name.endswith('.txt') or
                name.endswith('.ttl.in')):
                files += [j]

    bld(rule   = bld_book_src,
        source = files,
        target = 'book.txt')

    bld(rule   = 'asciidoc -b html -o ${TGT} ${SRC}',
        source = 'book.txt',
        target = 'book.html')
    
