#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import waflib.Logs as Logs

# Variables for 'waf dist'
APPNAME = 'lv2-event'
VERSION = '1.2'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)
    autowaf.display_msg(conf, "LV2 bundle directory",
                        conf.env['LV2DIR'])
    print('')

def build(bld):
    bld.install_files('${LV2DIR}/event.lv2',
                      'event.ttl event.h event-helpers.h manifest.ttl')

    bld.add_post_fun(warn_lv2config)

def warn_lv2config(ctx):
    if ctx.cmd == 'install':
        Logs.warn('''
* LV2 Extension Installed
* You need to run lv2config to update extension headers
''')
